version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=hello_db
      - POSTGRES_USER=hello_user
      - POSTGRES_PASSWORD=hello_password
